name: Angular Automation
on:
  push:
    branches: [development,RC_*]
env:
  SERVER: CIN
  NUGET_PATH: C:\NuGet\nuget.exe
  MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\msbuild.exe
  CINR_DEPLOY_PATH: \\HF2CINMYDLW01.amr.corp.intel.com\MyDeals
  CINR_DEPLOY_SERVER: HF2CINMYDLW01.amr.corp.intel.com

jobs:     
  Restore-packages:
     if: github.repository == 'intel-innersource/applications.web.mydeals.webui'
     runs-on: [self-hosted, mydeals-runner01]
     steps:
       - name: Checkout Directory
         uses: actions/checkout@master
       - name: Restore NUGET Packages 
         run: |
            echo "RUN NUGET Packages script at ${{env.NUGET_PATH}}"
            ./scripts/build_env.ps1 'nuget' '${{env.NUGET_PATH}}' '${{github.workspace}}'

  Build-Angular:
    if: github.repository == 'intel-innersource/applications.web.mydeals.webui'
    runs-on: [self-hosted, mydeals-runner01]
    needs: Restore-packages
    steps:
       - name: NPM Install 
         run: |
           ./scripts/build_env.ps1 'NPMInstall' 'path' '${{github.workspace}}'
       - name: NPM Build
         run: |
           ./scripts/build_env.ps1 'NPMBuild' 'path' '${{github.workspace}}'
         env:
           KENDO_UI_LICENSE: ${{ secrets.KENDO_UI_LICENSE }}
       - name: MS build publish
         run: |
            ./scripts/build_env.ps1 'MSBuild' '${{env.MSBUILD_PATH}}' '${{github.workspace}}'

  Angular_deploy:
    if: github.repository == 'intel-innersource/applications.web.mydeals.webui'
    runs-on: [self-hosted, mydeals-runner01]
    needs: Build-Angular
    steps:
       - name:  Move Publish Site 
         run: |
           ./scripts/build_env.ps1 'MovePublish' '${{env.CINR_DEPLOY_PATH}}' '${{github.workspace}}'
       - name:  Generate Client Zip Module
         run: |
           ./scripts/build_env.ps1 'ClientZip' '${{env.CINR_DEPLOY_PATH}}' '${{github.workspace}}'

       - name:  Remove Client Zip
         run: |
           ./scripts/deploy_env.ps1 'RemoveZipENV' '${{ secrets.USN }}' '${{ secrets.PWD }}' '${{env.SERVER}}'
       - name:  Copy Client Zip
         run: |
           ./scripts/deploy_env.ps1 'CopyZipENV' '${{ secrets.USN }}' '${{ secrets.PWD }}' '${{env.SERVER}}'
       - name:  Deploy Client App
         run: |
           ./scripts/deploy_env.ps1 'DeployENV' '${{ secrets.USN }}' '${{ secrets.PWD }}' '${{env.SERVER}}'
  
 